# Generated by Django 4.0.2 on 2022-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_answer_alter_question_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
