# Generated by Django 4.0.2 on 2022-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='min',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
