# Generated by Django 4.0.2 on 2022-03-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
