# Generated by Django 4.0.2 on 2022-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(blank=True, choices=[('science', 'science'), ('Art', 'Art')], max_length=20, null=True),
        ),
    ]
