# Generated by Django 4.0.2 on 2022-03-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_mobile_student_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
